reminiscence/main/urls.py
from django.conf.urls import patterns, include, url

from reminiscence.main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^pagina2/', views.pagina2, name='pagina2'),
    url(r'^luoghi/', views.luoghi, name='luoghi'),
#
# URL LOGIN
#
    url(r'^login/', views.login, name='login'),
    url(r'^verifica/', views.verifica, name='verifica'),
    
#
# URL DI INSERIMENTO RICORDO
#
    url(r'^add/', views.verificaAdd, name='add'),
    
#
# URL DI ISCRIZIONE AL SERVIZIO
#
    url(r'^account/', views.account, name='account'),
    url(r'^conferma/', views.conferma, name='conferma'),
    url(r'^fineAccount/', views.paginaConfermaAccount, name='fineAccount'),
    
#
# URL DI VISUALIZZAZIONE RICORDO
#
    url(r'^home/', views.visualizzaRicordi, name='homepage'),
    
# URL DI TIMELINE

    url(r'^timeline/', views.timeline, name='timeline'),
    url(r'^provatl/', views.provaTL, name='provaTL'),
)

reminiscence/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'reminiscence.views.home', name='home'),
    # url(r'^reminiscence/', include('reminiscence.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    
    url(r'^main/', include('reminiscence.main.urls', namespace="main")),
    url(r'^admin/', include(admin.site.urls)),
   
)

reminiscence/main/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

		
class Regione(models.Model):
	regione = models.CharField(max_length=80)
	def __unicode__(self):
		return str(self.regione)

class Provincia(models.Model):
	provincia = models.CharField(max_length=80)
	regione = models.ForeignKey(Regione)
	def __unicode__(self):
		return str(self.provincia)

class Comune(models.Model):
	provincia = models.ForeignKey(Provincia)
	comune = models.CharField(max_length=80)
	def __unicode__(self):
		return str(self.comune)
		

class Anziano(models.Model):
    nome= models.CharField(max_length=50)
    cognome= models.CharField(max_length=50 )
    anno_nascita= models.CharField(max_length = 4)
    mese_nascita= models.CharField(max_length = 2)
    giorno_nascita= models.CharField(max_length = 2)
    luogo_nascita= models.ForeignKey(Comune)
    email=models.CharField(max_length=200)
    password= models.CharField(max_length=50)
    def __unicode__(self):
		return str(self.cognome)
	
	
class Memoria(models.Model):
    IDAnziano=models.ForeignKey(Anziano)
    titolo= models.CharField(max_length=200)
    descrizione= models.CharField(max_length=1000)
    def __unicode__(self):
		return str(self.titolo)

class Decade(models.Model):
    decade= models.CharField(max_length=10)
    def __unicode__(self):
		return str(self.decade)
		
class Suggerimento(models.Model):
    titolo= models.CharField(max_length=200)
    descrizione= models.CharField(max_length=1000)
    tipoContenuto= models.CharField(max_length=200)
    contenuto = models.CharField(max_length=300)
    def __unicode__(self):
		return str(self.titolo)
		
class si_svolge_memoria(models.Model):
    IDDecade= models.ForeignKey(Decade)
    IDMemoria=models.ForeignKey(Memoria)
    conchi = models.CharField(max_length=200)
    luogo = models.CharField(max_length=50)
    indice = models.FloatField(max_length=20)
    anno= models.CharField(max_length = 4)
    mese= models.CharField(max_length = 2)
    giorno= models.CharField(max_length = 2)
    
class si_svolge_Suggerimento (models.Model):
    IDDecade= models.ForeignKey(Decade)
    IDSuggerimento=models.ForeignKey(Suggerimento)
    luogo = models.CharField(max_length=50)
    anno= models.CharField(max_length = 4)
    mese= models.CharField(max_length = 2)
    giorno= models.CharField(max_length = 2)
    
class Media (models.Model):
	IDMemoria = models.ForeignKey(Memoria)
	titolo = models.CharField(max_length=203)
	descrizione = models.CharField(max_length=300)
	link = models.CharField(max_length=200)
	

class Hint (models.Model):
	titolo = models.CharField(max_length=260)
	descrizione = models.CharField(max_length=300)
	link = models.CharField(max_length=200)
	IDDecade= models.ForeignKey(Decade)
	anno= models.CharField(max_length = 4)
	tipo = models.CharField(max_length = 15)
	indice = models.FloatField(max_length = 25)
	def __unicode__(self):
		return str(self.titolo)



	

reminiscence/main/views.py
# Create your views here.
from django.http import HttpResponse
from django.template import Context, loader
from django.shortcuts import render
from django.utils import simplejson as json
from reminiscence.main.models import Comune, Provincia, Regione, Anziano,Memoria,si_svolge_memoria,Decade, Hint
from django.views.decorators.csrf import csrf_exempt
from django.utils.safestring import SafeString

# metodo di chiamata non efficiente qui sotto

def index(request):
	return render(request, 'main/index.html')
	
def pagina2(request):
	template = loader.get_template('main/pagina2.html')
	context = Context({})
	return HttpResponse(template.render(context))

def luoghi(request):
	comune = 1
	regione = 2
	comprov = 3
	context = {'comune':comune,'reg':regione, 'comprov':comprov}
	return render(request, 'main/luoghi.html', context)

# metodo di chiamata piu efficiente (request sempre necessario)
	


#
# PAGINA DI LOGIN
#
#
#Visualizza la pagina di login
#	


def login(request):
	return render(request, 'main/nuovologin/login.html')


#
#Verifica i dati inseriti nella pagina di login
#


def verifica(request):
	name = request.POST.get('firstname')
	passw = request.POST.get('password')

	
	b = get_or_none(Anziano,nome=name)
	
	if b is None:
		
		return render(request, 'main/nuovologin/login.html')
	
	if passw == b.password:
		risp = 'SI'
	else:
		return render(request, 'main/nuovologin/login.html')
	    
	context = {'name':name, 'pass': str(b.password), 'risp':risp, 'anno': str(b.anno_nascita), 'id': str(b.id)}
	return render(request, 'main/timeline/timeline.html', context)

#
# PAGINA DI ISCRIZIONE
#

def account(request):
	giri = [i for i in range(1900, 2013)]
	giornimese = [i for i in range(1, 32)]
	trento = Provincia.objects.get(pk=22)
	bolzano = Provincia.objects.get(pk=21)
	comtn = Comune.objects.filter(provincia=trento)
	combz = Comune.objects.filter(provincia=bolzano)
	
	context = {'giri':giri, 'giornimese':giornimese,'ctn':comtn, 'cbz':combz}
	return render(request, 'main/account/creazioneAccount.html', context)



#
# Conferma e verifica dati
#
def conferma2(request):

	user = request.POST.get('username')
	com = request.POST.get('paese')
	print com
	giorno = request.POST.get('select_choice_day')
	mese = request.POST.get('select_choice_month')
	anno = request.POST.get('select_choice_year')
	pass1 = request.POST.get('password')
	pass2 = request.POST.get('password2')
	email = request.POST.get('email')
	
	c = get_or_none(Comune,comune='Trento')

	a = Anziano()
	a.nome = user
	a.anno_nascita = anno
	a.mese_nascita = mese
	a.giorno_nascita = giorno
	a.luogo_nascita = c
	a.email = email
	a.password = pass1
	a.save()
	return render(request, 'main/account/confermaAccount.html')

	
#
#prova di implementazione salvataggio di un nuovo utente nel db tramite json
#
#@ajax(require='POST')
@csrf_exempt
def conferma(request):#se vogliamo provarla davvero e usarla al posto di conferma(request) basta rinominare le due funz
	
	#import pdb; pdb.set_trace()
	json_data=request.POST.get('json')
	json_data=simplejson.loads(request.body)
	
	a=Anziano()
	t = get_or_none(Comune, comune="Trento")
	a.nome = json_data["nome"]
	print("porcodue "+json_data["nome"])*300
	a.anno_nascita = json_data["anno_nascita"]
	a.mese_nascita = json_data["mese_nascita"]
	a.giorno_nascita = json_data["giorno_nascita"]
	a.luogo_nascita = t # json_data["luogo_nascita]
	a.email = json_data["email"]
	a.password = json_data["password"]
	a.save()
	return render(request, 'main/account/confermaAccount.html')
	


def paginaConfermaAccount(request):
	return render(request, 'main/account/confermaAccount.html')




	
#
# HOMEPAGE (PAGINA VISUALIZZAZIONE MEMORIA)
#	

def visualizzaRicordi(request):
	return render(request, 'main/home.html')
	
#
# INSERIMENTO RICORDO 
#	
	
#aggiunta ricordo, pagina 1...	
def add(request):
	return render(request, 'main/aggiungi/aggiungiRicordo.html')


#
#verifica i dati aggiunti in aggiungiRicordo
#

def verificaAdd(request):
	dove = request.POST.get('luogo')
	quando_decade = request.POST.get('quando-decade')
	quando_mese = request.POST.get('quando-mese')
	quando_giorno = request.POST.get('quando-giorno')
	anno = request.POST.get('anno')
	dove = request.POST.get('luogo')
	con = request.POST.get('conchi')
	titolo= request.POST.get('titolo')
	descrizione = request.POST.get('descrizione')
	
	print dove, quando_decade, quando_mese, quando_giorno, anno, dove, titolo, descrizione
		
		#preleva ID Anziano (da modificare, deve prendere l'id dell'anziano loggato)	
	a=Anziano.objects.get(nome='Andrea')
		
		#crea un nuovo record in Memoria inizializzandolo solo con IDAnziano, il resto verra aggiunto dopo (necessario per creare si_svolge_memoria)
	m=Memoria(IDAnziano=a)
	m.titolo = titolo
	m.descrizione = descrizione
	m.save()
		
		#associa a d il record Decade corrispondente al valore della form select
	d=Decade.objects.get(decade=quando_decade)
		
		#crea si_svolge_memoria con tutti i campi inseriti
	s=si_svolge_memoria(IDDecade=d,IDMemoria=m,luogo=dove,anno=anno,mese=quando_mese, giorno = quando_giorno)
	s.save()
	
	return render(request,'main/aggiungi/confermaInsert.html')

#
# GESTIONE TIMELINE
#
 
def timeline (request):
	
	giri = [i for i in range(1900, 2013)]
	giornimese = [i for i in range(1, 32)]
	context = {'giri':giri, 'giornimese':giornimese}
	return render(request, 'main/timeline/timeline.html', context)


def provaTL(request):
	
	#per perfezionare l'estrazione dei dati fare in modo di prendere il nome dell'anziano (come fare non lo so, non ho la pagina)
	#b = get_or_none(Anziano, nome=name)
	lista = Memoria.objects.values('titolo', 'descrizione')[:3]
	jsonMem = str(json.dumps(list(lista)))
	
	lista2 = Hint.objects.values('titolo')
	jsonHint = str(json.dumps(list(lista2)))
	
	context = {'jsonMem':jsonMem, 'jsonHint':jsonHint}
	return render(request, 'main/nuovaTimeline/main.html', context)




#
#QUI SOTTO INSERIRE SOLO LE FUNZIONI GENERICHE
#




#funzione che controlla se un record esiste. CONSIGLIO DI USARLA OGNI VOLTA CHE SERVE PRELEVARE UN RECORD
def get_or_none(model, **kwargs):
	try:
		return model.objects.get(**kwargs)
	except model.DoesNotExist:
		return None
        
#se serve prelevare piu di un record, usare model.objects.filter(cond)

reminiscence/main/templates/main/account/confermaAccount.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<body>

<h1> ACCOUNT CREATO! </h1>

Verrai rimandato alla pagina di login tra 5 secondi
<script>
 $(document).ready(function () {
		setTimeout(function() {
      		parent.location="{% url 'main:login' %}";
		}, 5000);        });
</script>
</body>
</html>

reminiscence/main/templates/main/account/creazioneAccount.html
	<!DOCTYPE html>
<html>
    
    <head>
        <meta charset="utf-8">
        <title>Reminiscence</title>

<!-- modificare con tag django { static } (vedere file di aggiunta ricordo per avere un'idea) -->
{% load staticfiles %}    
		   
	    <link href="{% static 'css/stili/blu.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'css/jquery.mobile.structure-1.3.0.min.css' %}" rel="stylesheet" type="text/css" />
        <script src="{% static 'js/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/jquery.mobile-1.3.0.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/account/creazionescript.js' %}" type="text/javascript"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'css/aggiungi/creazionestyle.css' %}">
        <script>
        	var rimanda = function() {parent.location="{% url 'main:login' %}";};

		
			var utente=function(){
		    this.nome="";
		    this.cognome="";
		    this.anno_nascita="";
		    this.mese_nascita="";
		    this.giorno_nascita="";
		    this.luogo_nascita="";
		    this.email="";
		    this.password="";
		
		    };
		   
		    var u=new utente();
			var issues=false;
				
        	var controlla = function() { if(view()===true){final();}else{return false;}};
        		
        	var view = function() {
				var username=document.getElementById('user').value;
				var password=document.getElementById('pass').value;
				var password2=document.getElementById('pass2').value;
				var giorno=document.getElementById('select_choice_day').value;
				var mese=document.getElementById('select_choice_month').value;
				var anno=document.getElementById('select_choice_year').value;
				
				console.log(username);
				console.log(password);
				console.log(password2);
				
				
				if(username==="")
				{
				alert("il nome utente non è stato inserito. Per favore, inseriscilo");
				issues = true;
				}
				
				if(giorno==="" || mese===""|| anno==="")
				{
					alert("la data di nascita non è stata inserita nel modo corretto. Per favore, ricontrollala");
					issues = true;
				}
				
				if(password.lenght<6)
				{
					alert("la password non è abbastanza lunga, inserisci almeno 6 caratteri");
					issues = true;	
				}
        		
        		if(password==="" || password2==="")
        		{
					alert("la password non è stata inserita. Per favore, inseriscila");
					issues = true;
				}
			
				if(password!=password2)
        		{
					alert("le password non corrispondono. Per favore, correggile");
					issues = true;
				}
				
				if(issues===false)
				{
					alert("entro in final");
					return true;
				}
				
				return false;
				
        	};
			
			    var final = function(){
			    
					u.email=$("#email").val();
					u.password=$("#pass").val();

					u.anno_nascita=$("#select_choice_year").val();
					alert(u.nome+" "+u.cognome+" "+u.anno_nascita+" "+u.mese_nascita+" "+u.giorno_nascita+" "+u.luogo_nascita+" "+u.email+" "+u.password);
	
					$.ajax({
					  type:"POST",
					  url: " {% url 'main:conferma' %} ",
					  data: JSON.stringify(u),
					  processData: false,
					  dataType: "json",
					  success:function() {}
							});
						
					return true;
						};
			
			
        </script>
        
    </head>
    <body>
    <form name="DatiPersonali" id="DatiPersonali" onSubmit="return controlla();" action="{% url 'main:fineAccount' %}" method="POST">
    {% csrf_token %}
    
	<div data-role="page" id="NamePage">
            <div data-role="header">
                	<a  style="width:25%;margin-left:5%;top:5%;" data-role="button" onclick="rimanda()" data-transition="slide" >Esci</a>      
  		


					<p class="header">Dati Personali</p>


            </div>
            <div data-role="content" data-theme="a">
                 <h2 >Nome</h2>

                <div data-role="fieldcontain"  class="ui-hide-label" style="width:75%;margin-left:auto;margin-right:auto" >
                    <input type="text"  name="username" id="user" value="" placeholder="Come ti chiami?" />



<!--------------------------------------------------------------- qui il primo input NOME--------------------------------------->			

                </div>
                 <h2 >Provenienza</h2>

<!---------------------------------------------------------qui il secondo input DOVE---------------------------------------->

                <div data-demo-html="true" style="width:75%;margin-left:auto;margin-right:auto" >
                    <ul data-role="listview" name="paese" data-filter="true" id="ComList" data-filter-reveal="true" data-filter-placeholder="Dove sei vissuto piu a lungo?">
                         {% for i in ctn %}
        				  <li >{{i}}</li>
						  {%endfor%}
						{% for i in cbz %}
        				  <li>{{i}}</li>
						  {%endfor%}
                    </ul>
                </div>
            </div>
            <div data-role="footer">
        <a  style="width:45%;margin-left:50%;top:35%;" onclick="nomeluogo()" href="#BirthPage" data-role="button" data-transition="slide">Avanti</a>
    
            </div>
        </div>
        <script>
$(document).ready(function(){
$('#ComList').children('li').on('click', function () {
  u.luogo_nascita=this.innerHTML
});
});


function nomeluogo(){
u.nome=$("#user").val();

}
	</script>
        
        <div data-role="page" id="BirthPage" style="width:100%;height:100%">
            <div data-role="header">
             <a  style="width:25%;margin-left:5%;top:5%;"  href="#NamePage" data-role="button" data-transition="slide">Indietro</a> 
                  <p class="header">Dati Personali</p>

            </div>
            <div  data-role="content" data-theme="a">
                 <h2  style="text-align:center;">Data di nascita</h2>


<!--------------------------------------qui il terzo input QUANDO - GIORNO ------------------------------------------------------->

<div id="selectDate" data-role="controlgroup" data-type="horizontal" >
    <label for="select_choice_day">Day</label>
                        <select name="select_choice_day" id="select_choice_day" >
                            <option value = "">Giorno</option>
                          {% for i in giornimese %}
        				  <option value={{i}}>{{i}}</option>
						  {%endfor%}
                        </select>


<!--------------------------------------qui il quarto input QUANDO - MESE ------------------------------------------------------->


                        <label for="select_choice_month">Month</label>
                        <select name="select_choice_month" id="select_choice_month">
                            <option value="">Mese</option>
                            <option value="jan">Gennaio</option>
                            <option value="feb">Febbraio</option>
                            <option value="mar">Marzo</option>
                            <option value="apr">Aprile</option>
                            <option value="may">Maggio</option>
                            <option value="jun">Giugno</option>
                            <option value="jul">Luglio</option>
                            <option value="aug">Agosto</option>
                            <option value="sep">Settembre</option>
                            <option value="oct">Ottobre</option>
                            <option value="nov">Novembre</option>
                            <option value="dic">Dicembre</option>
                        </select>


<!--------------------------------------qui il quinto input QUANDO - ANNO ------------------------------------------------------->

                        <label for="select_choice_year">Year</label>
                        <select name="select_choice_year" id="select_choice_year">
                            <option value = "">Anno</option>
                            {% for i in giri %}
        					<option value={{i}}>{{i}}</option>
							{%endfor%}                        
						</select>
			</div>
               
            </div>
            <div data-role="footer">
             <a  style="width:45%;margin-left:50%;top:35%;" onclick="data()"  href="#PasswordPage" data-role="button" data-transition="slide">Avanti</a>
            
            </div>
        </div>
<script>
        function data(){
u.mese_nascita=$("#select_choice_day").val();
u.giorno_nascita=$("#select_choice_month").val();
u.anno_nascita=$("#select_choice_year").val();

}
 </script>  
        <div data-role="page" id="PasswordPage">
            <div data-role="header">
            <a  style="width:25%;margin-left:5%;top:5%;"  href="#BirthPage" data-role="button" data-transition="slide">Indietro</a> 
                  <p class="header">Dati Personali</p>

            </div>
            <div data-role="content" data-theme="a">
                <div data-role="fieldcontain" >
                    <div >
                         <h2 >Inserire Parola Chiave</h2>

                        <input type="password" name="password" id="pass" value="" />
                    </div>

<!--------------------------------------qui il sesto input Password - 1 ------------------------------------------------------->

                    <div >
                         <h2 >Reinserire Parola Chiave</h2>

                        <input type="password" name="password2" id="pass2" value="" />
                    </div>

<!--------------------------------------qui il settimo input Password - 2 ------------------------------------------------------->
                    <div >
                         <h2 >E-mail</h2>
						<input type="email" name="email" id="email" value="" placeholder="tua o di un parente.."/>
                    </div>

<!--------------------------------------qui l'ottavo input e-mail ------------------------------------------------------->

                </div>
            </div>

            <div data-role="footer">
            <input  style="width:45%;margin-left:50%;top:35%;" type="submit" value="Fine">
            </div>
        </div>
        <script>

 </script>  
	</form>
	</body>
</html>